[2024-12-16T15:59:36.192+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-12-16T15:59:33.655647+00:00 [queued]>
[2024-12-16T15:59:36.195+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-12-16T15:59:33.655647+00:00 [queued]>
[2024-12-16T15:59:36.195+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-12-16T15:59:36.207+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-12-16 15:59:33.655647+00:00
[2024-12-16T15:59:36.210+0000] {standard_task_runner.py:57} INFO - Started process 64986 to run task
[2024-12-16T15:59:36.212+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-12-16T15:59:33.655647+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmprq4zmzod']
[2024-12-16T15:59:36.213+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask extract_task
[2024-12-16T15:59:36.235+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-12-16T15:59:33.655647+00:00 [running]> on host codespaces-586565
[2024-12-16T15:59:36.267+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T15:59:33.655647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T15:59:33.655647+00:00'
[2024-12-16T15:59:36.268+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-16T15:59:36.269+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget --no-verbose --tries=3 --timeout=30 -O /lab/challenges/challenge-extract-dag.csv https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/constituents.csv']
[2024-12-16T15:59:36.275+0000] {subprocess.py:86} INFO - Output:
[2024-12-16T15:59:36.278+0000] {subprocess.py:93} INFO - /lab/challenges/challenge-extract-dag.csv: No such file or directory
[2024-12-16T15:59:36.279+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-16T15:59:36.283+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-16T15:59:36.285+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=challenge_dag, task_id=extract_task, execution_date=20241216T155933, start_date=20241216T155936, end_date=20241216T155936
[2024-12-16T15:59:36.293+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 64986)
[2024-12-16T15:59:36.304+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-16T15:59:36.316+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
