[2024-12-16T16:14:43.117+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-12-16T16:09:37.703933+00:00 [queued]>
[2024-12-16T16:14:43.122+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-12-16T16:09:37.703933+00:00 [queued]>
[2024-12-16T16:14:43.123+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-16T16:14:43.138+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-12-16 16:09:37.703933+00:00
[2024-12-16T16:14:43.142+0000] {standard_task_runner.py:57} INFO - Started process 76158 to run task
[2024-12-16T16:14:43.145+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-12-16T16:09:37.703933+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmp4t7_wb00']
[2024-12-16T16:14:43.146+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask extract_task
[2024-12-16T16:14:43.182+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-12-16T16:09:37.703933+00:00 [running]> on host codespaces-586565
[2024-12-16T16:14:43.229+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T16:09:37.703933+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-16T16:09:37.703933+00:00'
[2024-12-16T16:14:43.230+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-16T16:14:43.231+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -o /lab/challenges/challenge-extract-dag.csv https://raw.githubusercontent.com/LinkedInLearning/hands-on-introduction-data-engineering-4395021/main/data/constituents.csv']
[2024-12-16T16:14:43.239+0000] {subprocess.py:86} INFO - Output:
[2024-12-16T16:14:43.249+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-12-16T16:14:43.249+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-12-16T16:14:43.445+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file /lab/challenges/challenge-extract-dag.csv: No
[2024-12-16T16:14:43.445+0000] {subprocess.py:93} INFO - Warning: such file or directory
[2024-12-16T16:14:43.445+0000] {subprocess.py:93} INFO -   7 18676    7  1369    0     0   6965      0  0:00:02 --:--:--  0:00:02  6984
[2024-12-16T16:14:43.445+0000] {subprocess.py:93} INFO - curl: (23) Failure writing output to destination
[2024-12-16T16:14:43.447+0000] {subprocess.py:97} INFO - Command exited with return code 23
[2024-12-16T16:14:43.451+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 23.
[2024-12-16T16:14:43.453+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=challenge_dag, task_id=extract_task, execution_date=20241216T160937, start_date=20241216T161443, end_date=20241216T161443
[2024-12-16T16:14:43.463+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 66 for task extract_task (Bash command failed. The command returned a non-zero exit code 23.; 76158)
[2024-12-16T16:14:43.481+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-16T16:14:43.493+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
