[2024-12-13T17:23:32.777+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_dag.load_csv_to_sqlite manual__2024-12-13T17:18:27.181473+00:00 [queued]>
[2024-12-13T17:23:32.781+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_dag.load_csv_to_sqlite manual__2024-12-13T17:18:27.181473+00:00 [queued]>
[2024-12-13T17:23:32.781+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2024-12-13T17:23:32.791+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_csv_to_sqlite> on 2024-12-13 17:18:27.181473+00:00
[2024-12-13T17:23:32.794+0000] {standard_task_runner.py:57} INFO - Started process 10749 to run task
[2024-12-13T17:23:32.797+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_dag', 'load_csv_to_sqlite', 'manual__2024-12-13T17:18:27.181473+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/load_dag.py', '--cfg-path', '/tmp/tmpano51jsd']
[2024-12-13T17:23:32.799+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask load_csv_to_sqlite
[2024-12-13T17:23:32.828+0000] {task_command.py:410} INFO - Running <TaskInstance: load_dag.load_csv_to_sqlite manual__2024-12-13T17:18:27.181473+00:00 [running]> on host codespaces-586565
[2024-12-13T17:23:32.859+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_dag' AIRFLOW_CTX_TASK_ID='load_csv_to_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T17:18:27.181473+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T17:18:27.181473+00:00'
[2024-12-13T17:23:32.860+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-13T17:23:32.860+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sqlite3 /workspace/airflow-load-db.db                   ".mode csv"                   ".import airflow-transform-data.csv top_level_domains"']
[2024-12-13T17:23:32.867+0000] {subprocess.py:86} INFO - Output:
[2024-12-13T17:23:32.869+0000] {subprocess.py:93} INFO - Error: unable to open database "/workspace/airflow-load-db.db": unable to open database file
[2024-12-13T17:23:32.869+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-13T17:23:32.873+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-13T17:23:32.875+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=load_dag, task_id=load_csv_to_sqlite, execution_date=20241213T171827, start_date=20241213T172332, end_date=20241213T172332
[2024-12-13T17:23:32.883+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task load_csv_to_sqlite (Bash command failed. The command returned a non-zero exit code 1.; 10749)
[2024-12-13T17:23:32.894+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T17:23:32.902+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
