[2024-12-13T17:26:48.257+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [queued]>
[2024-12-13T17:26:48.261+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [queued]>
[2024-12-13T17:26:48.261+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2024-12-13T17:26:48.270+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-12-13 13:50:25.391603+00:00
[2024-12-13T17:26:48.273+0000] {standard_task_runner.py:57} INFO - Started process 12344 to run task
[2024-12-13T17:26:48.276+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-12-13T13:50:25.391603+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpja417d3j']
[2024-12-13T17:26:48.277+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask extract_task
[2024-12-13T17:26:48.301+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [running]> on host codespaces-586565
[2024-12-13T17:26:48.331+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T13:50:25.391603+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T13:50:25.391603+00:00'
[2024-12-13T17:26:48.332+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-13T17:26:48.333+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -O /workspace/lab/orchestrated/airflow-extract-data.csv https://lnkd.in/gfENQi7K']
[2024-12-13T17:26:48.339+0000] {subprocess.py:86} INFO - Output:
[2024-12-13T17:26:48.341+0000] {subprocess.py:93} INFO - /workspace/lab/orchestrated/airflow-extract-data.csv: No such file or directory
[2024-12-13T17:26:48.342+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-13T17:26:48.346+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-13T17:26:48.349+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=extract_dag, task_id=extract_task, execution_date=20241213T135025, start_date=20241213T172648, end_date=20241213T172648
[2024-12-13T17:26:48.357+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 12344)
[2024-12-13T17:26:48.368+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T17:26:48.376+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
