[2024-12-13T17:21:45.851+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [queued]>
[2024-12-13T17:21:45.856+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [queued]>
[2024-12-13T17:21:45.856+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 4
[2024-12-13T17:21:45.867+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-12-13 13:50:25.391603+00:00
[2024-12-13T17:21:45.871+0000] {standard_task_runner.py:57} INFO - Started process 9905 to run task
[2024-12-13T17:21:45.873+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'extract_dag', 'extract_task', 'manual__2024-12-13T13:50:25.391603+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/extract_dag.py', '--cfg-path', '/tmp/tmpfj1dwejv']
[2024-12-13T17:21:45.874+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask extract_task
[2024-12-13T17:21:45.897+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_dag.extract_task manual__2024-12-13T13:50:25.391603+00:00 [running]> on host codespaces-586565
[2024-12-13T17:21:45.927+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T13:50:25.391603+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T13:50:25.391603+00:00'
[2024-12-13T17:21:45.928+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-13T17:21:45.929+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -O /workspace/lab/orchestrated/airflow-extract-data.csv https://lnkd.in/gfENQi7K']
[2024-12-13T17:21:45.934+0000] {subprocess.py:86} INFO - Output:
[2024-12-13T17:21:45.938+0000] {subprocess.py:93} INFO - /workspace/lab/orchestrated/airflow-extract-data.csv: No such file or directory
[2024-12-13T17:21:45.938+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-13T17:21:45.942+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-13T17:21:45.944+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_dag, task_id=extract_task, execution_date=20241213T135025, start_date=20241213T172145, end_date=20241213T172145
[2024-12-13T17:21:45.951+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task extract_task (Bash command failed. The command returned a non-zero exit code 1.; 9905)
[2024-12-13T17:21:45.965+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T17:21:45.973+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
